---
title: "被驯服的爱情？"
author: "思无邪"
date: "2025-08-21 20:58"
categories: [梦话]
---

观刘擎教授驯服爱欲视频有感

如今市面上关于爱情的书很多，但总的来看似乎是良莠不齐，而良的部分呢，似乎是比较少的。再看互联网关于爱情的观点或者说这些观点的理由，大体可以分为以下的几类：

1.把爱情的工具化

2.把爱情量化

什么是把爱情工具化呢？就是把爱情当作牟利的工具，典型的提问方式就是“爱情能给我带来什么好处呢？”

什么是把爱情量化呢？就是把恋爱中的种种行为量化成指标，然后像精算师或者会计一样计算每一项的得失盈亏。

以上两种观点都直接把爱情的神圣性，超越性彻底的消解了。于是很多人就说其实所谓的“爱情”根本就不存在。这样没有爱情就不是我们自己的问题了，而是爱情不存在的必然结果。但是如果这个说法你真的相信的话，那就太好了，这篇读后感后面的内容你也就根本不用看了。

但人们似乎并不是真的对这个说法感到满意，否则人们恐怕就不会为爱情感到焦虑或者失望，毕竟为了不存在的事情焦虑就有点杞人忧天了。

然后人们在焦虑中似乎就衍生出了一些应对爱情的“技巧”，当然我在这里无法全部顾及，但我想后面的内容如果你读完觉得有所认同的话，那大概市面上常见的技巧几乎都是无效的。

现在有种常见的说法是要在爱情中保持自己的“主体性”，大概意思就是不要让自己在爱情里收到伤害。衍生出的常见技巧就是欲擒故纵的一类，而衍生出的问题大概就是要找你爱的人还是爱你的人之类的。这些技巧和问题看起来似乎有些道理但是我想也有些问题。问题就是，我们追求爱情的目的是什么？是让自己不受伤害吗？其实这就揭示了今天的主题，就是我们似乎现在总有一种观点或者想法，就是驯服爱欲，如果爱情像宠物一样乖乖的很听话，好像就很好。这样的爱情就很有安全感，很有确定性。

你可能会觉得这样的爱情听起来相当的好啊，简直就是我追求的爱情。但其实有两个问题。一个问题就是驯服爱情一般来说是不可能的，因为爱情是两个人的事，而人有自己的主观意志，总是不可能别人驯服的；第二问题更难发现，但我认为也更加的关键，就是如果爱情真的被驯服了，几乎可以肯定地说，也丧失爱情最精彩的部分，就是爱情的生命力，这种生命力带给人们全新的体验，可以说是惊奇般的体验。

有人可能觉得惊奇挺好的，但我可不想被惊吓。于是很多人就想要凭运气找一个跟自己及其搭配的人。但其实只有自己才会完美的理解自己，某种意义上，这算是一种自恋而非自爱。

德国韩裔哲学家韩炳哲在《爱欲之死》认为爱情里的恋人是一个经典意义上的独一无二的他者，是令人着迷的，但同时也意味着不可控制的，有时是令人困惑的。他认为爱情的终结是由自恋和同质化导致的。这是什么意思呢？这意味着我们试图让爱情这种极具生命力的事情变成我们可以控制的，让我们自己感到舒服，保证自己安定的东西。韩在书里认为爱情作为一个他者，最重要的特质恰恰就是异己性，而我们试图那些保证自己安定的做法都和真正的接纳他者都是相反的。他认为我们不能把人标签化，或者叫量化，我们应该意识到人的个体性，也就是独一无二的感觉。

> 否定性的缺失导致了当今爱情的枯萎，成了可消费、可计算的享乐主义的对象。人们满足于追求同好者的那份舒适，放弃了对他者的渴望。被追求的是一种舒服的、最终缓慢沉淀在意识之内的熟悉感。超验性在当今的爱情中不复存在。
>
> <p align="right">——韩</p>

韩认为我们应该接纳他者，借助他者的力量重新打开自己，去感受真实的世界。

这种观点很好，但值得持保留观点。韩的观点有些过于神化他者了，他者作为一种异己性的力量对我们的否定性，这种否定性究竟最后会转化成自我转变的积极力量还是只是让我们丧失主体性的消极力量是有待商榷的。韩对当今这种计算性的，量化的，绩效导向的文化的批判，是否曾想到这种文化在刚刚出现时也是一种他者，我们对这种文化的简单接纳真的时只带来了好的结果吗？所以我们如果真如韩所说的简单的接纳他者，就恰恰陷入了他所批判的后果。