---
title: 新篇章：经济学，芜湖
author: 思无邪
draft: false
date: '2025-04-15'
categories:
- 经济学
---
为什么商业是最大的慈善？
<!--more-->

# 经济学在研究什么？

某种意义上，经济学研究的是“事与愿违”的规律。例如，颁布最低工资制度明明是用来保护低收入群体的，为什么低收入群体的境遇在颁布后却更糟了；颁布动物保护法是为了保护动物，为什么这些动物越保护越少了？

经济学研究的不是我们通常想的，工资太低就是资本家抢走了剩余价值，强迫资本家多发钱就解决了这种思路，而恰恰相反，经济学研究是为什么这些思路不起作用，到底什么样的办法会起作用，也就是好心为啥办不了好事。

# 理性人的假设？

一种很常见的说法是说，经济学的理论都是建立在理性人的假设之上的，但现实中很多人都是不理性的，所以经济学理论在现实中很多时候不起作用。我在初中时读过一套叫《怪诞行为学》的书，里面研究的是一种比较新的经济学，叫行为经济学，就是专门研究人的非理性决策的，某种意义上更像心理学。我看了那套书之后，也觉得经济学理论大概和现实会很脱节。这个问题其实经济学家很早就在争论了，在1950年，一个叫阿尔钦的年轻经济学教授发表了一篇《不确定性、进化和经济理论》对这个问题提出了非常深刻的见解，可以说，这篇论文是整个经济学大厦的基础。

阿尔钦的观点说起来其实很简单，就是达尔文的进化理论用到了市场里。市场需求就相当于自然选择的环境，只有那些符合市场需求的组织或者公司或者个人，才能存活下来。

举个例子，假设有三个傻子要开加油站，一个开在自家后院里，一个开在了山顶上，一个恰好就开在了大马路边。显然最后只有这个开在马路边的加油站才能存活下来。所以阿尔钦的观点是，是否理性其实根本不重要，正如例子的加油站，并非通过理性分析开到路边才获得成功，而是没有开在路边的加油站都被淘汰了，跟理性毫无关系！

这下我们可以回答一些比较经典的问题了，例如常有人问：到底是随大流更容易成功，还是特立独行更容易成功呢？根据阿尔钦的观点，其实成功与否根本与这些风格毫无关系，重要的是市场需要什么，从经验来说，一个市场需求十分稳定的行业，随大流可以模仿前辈的经验，更容易存活；而对于新兴领域，市场需求还并不稳定，一切都在探索中，技术日新月异，往往就需要特立独行一些了。和生物里面的自然选择一模一样吧。

# 商业是最大的慈善

## 世界银行的失败扶贫史

世界银行并非银行，而是一个国际扶贫机构。但是这个组织的业绩却一言难尽。伊斯特利在2006年的一本书《白人的负担》里写道：在非洲，如果每个儿童能拿到12美分打一针疫苗，死于疟疾的人数会减少一半，但是过去五十年，西方对非洲援助了高达2.3兆美元，却没有做到这一点；但是有趣的是，就在2005年7月16日这一天，英美两国却把900万册《哈利波特》从各地的仓库或者书商卓有成效的送到消费者手中。伊斯特利的问题是，为什么运送哈利波特这样的娱乐活动能非常高效的完成，但是援助非洲儿童这样严肃的事情，效率却如此低下呢？

## 慈善效率低下的原因

### 缺乏反馈

很重要的一点是市场有非常良好的反馈机制，但是慈善却没有。

举个例子，我在市场里卖牛肉面，10块钱一碗，顾客看到我卖牛肉面有两个选择，买或者不买。我作为老板，如果看到顾客总是过来看看却不买（或者看看自己的钱包发现马上就要亏得自己都吃不上牛肉面了），那我也有两个选择，提高质量，或者降低成本，否则我就像阿尔钦说的一样，被市场给淘汰掉。

但是慈善却没有这样的反馈机制。还是我，接着卖牛肉面，但这次不一样了，我是慈善机构，我的牛肉面不要钱，白送。那就会出现这样的情况，白送的牛肉面，那肯定大家都要，吃完之后下一碗还是白送，要不要，大概率也要。但是作为老板，我并不知道市场是否真的需要我的牛肉面。

### 委托代理问题

很多慈善机构因为花的不是自己的钱，干起活来认真程度就会大打折扣。

### 所托非人问题

很多地区的贫困正是由于当地政府造成的，但国际扶贫机构却还给他们拨款，指望他们拿拨款去扶贫，这是难以奏效的。

### 养懒汉

直接发钱会容易养懒汉，参考英国的福利制度。

从上面的几个原因就可以看出来，慈善行为往往无法达到预期。但是商业行为通过市场机制大幅、持续且高效的提高了人们的生活水平，所以商业才是最大的慈善。

### 关于扶贫的问题

虽然世界银行的扶贫效果很差，但是还是有不少扶贫是取得了非常好的成就的，例如中国的扶贫以及我想提到的里一本书，《穷人的银行家》，尤努斯博士通过小额贷款（10美元一个人左右）的方式极大的改善了他的故乡，孟加拉国的贫困问题。我们可以看到，几乎所有真正有效的扶贫，都不是通过直接发钱的方式来扶贫的。
