# _quarto.yml 的最终黄金配置 (已修正 lang 位置)
project:
  type: website

website:
  title: "思无邪的博客"
  site-url: "https://siwuxiee.github.io"
  description: "只是一些正确的废话和个人的偏见"
  
  navbar:
    right:
      - href: about.qmd
        text: "关于"

  search: true
  # --- 评论功能的完整配置 ---
  comments:
    giscus:
      repo: siwuxiee/siwuxiee.github.io
      repo-id: "R_kgDOPhjITg"             # <--- 需要替换
      category: "Announcements"         # 确保这是您选择的分类名
      category-id: "DIC_kwDOPhjITs4CuaXy" # <--- 需要替换
      mapping: "pathname"
      reactions-enabled: "1"
      emit-metadata: "0"
      theme: "preferred_color_scheme"
      lang: "zh-CN"
  # --- 配置结束 ---

format:
  html:
    theme: cosmo
    lang: zh-CN  # <--- lang 的正确位置在这里
    css: styles.css