# _quarto.yml 的最终正确配置
project:
  type: website

editor:
  render-on-save: true
  preview-mode: file
  
website:
  title: "只是一些正确的废话和个人的偏见"
  site-url: "https://siwuxiee.github.io"
  description: "只是一些正确的废话和个人的偏见"
  
  navbar:
    #right:
    #  - href: about.qmd
    #    text: "关于"

  search: true
  
  # --- 评论功能的修正后配置 ---
  comments:
    giscus:
      repo: siwuxiee/siwuxiee.github.io
      repo-id: "R_kgDOPhjITg"             # 请确认这是您自己的ID
      category: "Announcements"
      category-id: "DIC_kwDOPhjITs4CuaXy" # 请确认这是您自己的ID
      mapping: "pathname"
      reactions-enabled: true             # 已从 "1" 修正为 true
      theme: "preferred_color_scheme"
      # 无效的 emit-metadata 和 lang 选项已被移除
  # --- 配置结束 ---

format:
  html:
    theme: cosmo
    lang: zh-CN
    css: styles.css