---
title: 成本：放弃的最大价值
author: 思无邪
draft: false
date: '2025-04-17'
categories:
- 经济学
---
别只盯着钱
<!--more-->

### 成本是什么？

#### 定义

成本是放弃了的最大代价。什么意思呢？举个简单的例子。例如说你买了一块地皮，这块地皮有非常的多的用途，你可以盖居民楼，也可以建一个采石场，或者建一个工厂，如果这块地下面有矿产资源或者石油资源你也可以开采这些资源来赚钱，或者只是让它空着什么也不干。你会发现一个地皮有很多种用法，每种用法可以给你带来不同的收入，但你只能选择其中一种来赚钱，如果你选择盖居民楼，就不能建工厂，而你的成本就是在你选择了某一个选项后，放弃的选项里价值最高的那个。

#### 沉没成本并非成本

成本是放弃的最大代价，如果没有什么可以放弃的，就没有成本。沉没成本是已经发生且不可收回的支出。所以我们可以看到，成本这个概念是指向未来的，而不是指向过去的。

#### 成本并不简单

虽然成本定义看着很简单易懂，但是实际上是深不可测的，原因很简单，你说成本是放弃了的最高代价，但是我在尝试前，我怎么知道我放弃的最高代价是多少呢？例如一块地皮，我盖了居民楼来赚钱，我根本不知道盖成采石场或者工厂能赚多少钱啊，而且很有可能还有很多我没想象出来的用途，没准那些用途更赚钱呢。

这个问题的解决目前只能靠想象，你要能想象一个资源能用什么样的方式来赚钱，如果你能想象出来方式，具体赚多少钱倒是可以通过市场调研等手段做一个大致的估计，虽然也不总是准确的。

这种想象让一代又一代的经济学大师在成本上下很大功夫去研究。提出了很多关于成本的概念，像是公共品使用成本，制度变迁成本，社会成本，竞争本身的成本等等，未来我们都会慢慢学到。

### 成本由别人决定

其实很好理解，如果你拥有某个资产，这个资产的最高价值并不是你自己说了算，而是由市场对它的预期决定的。举个例子，假设你在鼓楼东大街有一个祖传铺位，专门卖早餐，这个铺位的成本是除了卖早餐以外其他赚钱方式里最赚钱的那一个。例如如果有人看上了这个铺位，愿意出价10万每月租下来，那你用这个铺位卖早餐的成本就是10万每月。

### 别只盯着钱

货币成本并非全部成本，我们应该更多关注全本成本而非货币成本。举个例子，我们去淘二手货，虽然可能价格会低一些，但是我们可能需要花费更多的时间，买到假劣产品的可能性也增加了，所以总的成本是高了还是低了其实并不好说。

#### 中间商让商品更便宜

很多人都讨厌中间商，认为中间商赚了很多差价，甚至有人做了一些调查，说从超市里一块钱的一瓶水实际上出厂价只有一毛钱，中间商赚走了90%！这种看法其实非常错误。如果我们不经过中间商，直接跑到农田里买青菜，跑到屠宰场去买肉，那我们付出的成本将变得非常的高。有些人可能不理解为什么，我们单拿物流这一项来说，假设一个小区是10个家庭，如果没有超市，大家都要去农田里买蔬菜，那每个家庭都需要付出一次物流的费用，但如果是超市集中采购的话，超市只需要跑一趟就能买很多的货物，供小区里的人们购买，其实可以看到整个小区买蔬菜的物流成本几乎降低了10倍，这还只是假设小区只有10个家庭且只考虑物流成本的情况下。经济学告诉我们，即使统计数据是准确的，中间商赚取了90%的钱，但由于中间商之间也在竞争（例如一个小区附近可能由三家超市互相竞争），这其实已经是中间商能赚取的最低比例了。
