---
title: 确定性：大部分时候只是一种幻想
author: 思无邪
draft: false
date: '2025-03-25'
categories:
- 梦话
---
确定性，名词，一种非常吸引人的、对未来的幻想。
<!--more-->

前天在火车上与$l$同学谈论了一些类似人生愿望的话题，颇有启发，故写下。

我发现很多人在生活当中感到焦虑似乎很多时候都因为希望去控制一些自己无法控制的事情，希望自己能找到一条非常明确的通往目标的道路。例如如果我相当“科学家”，那一个经典且传统的路径就是好好学习基础知识-->读研究生-->读博士，还大概率需要读个外国博士-->读很难看懂的论文-->发表很难看懂的论文-->组建自己的实验室，到这步可以说初步称为了一个科学家了。这条路径虽然看起来明白无误，但是却像一个精密但脆弱的仪器，容错率极低，而且是我们常说的“系统误差”，不可改进。往往沿着这个路径思考下去，很快就会让人产生放弃的想法，感觉一切没有什么意义。

因为这里面有太多不属于自己可以控制的部分，每个环节其实有相当大的比例不受自己控制，例如发表paper就很难受自己控制，没有人能保证怎样做就一定能发表一篇很好的论文，如果有这种方法，那论文也就可以像工业品一样，流水线式的哗哗生产出来了（某种意义上和现状挺像）。

在生活中，大部分时候事情不是我们可以控制的，控制不了我们的过去、我们的原生家庭、周围的环境，或者别人对自己的评价。如果我们一直把想法放在这些问题上，那恐怕就只能一直焦虑着。

我们也可以试着只去想我们能控制的部分，把这部分列成一个计划，这个计划就是可以充分执行的，但同时也要意识到，任何计划都不保证事情最后的成功，也不能保证达到最终的目标。

但是为什么呢？我们为什么喜欢一直喜欢想我们控制不了的东西呢？我有个猜测是可能因为我们控制不了的事情是大多数事情，而控制得了得事情是非常小的一部分，所以跟控制不了的事情比，我们控制不了的事情显得非常的“平庸”，而且不能立刻就改变结局，所以我们宁愿沉浸在那些控制不了的幻想里。

我记得曾经有个非常有趣的“四象限法”，用来做计划，简直是完全扯淡的。把事情分为所谓的“重要紧急”或者“重要不紧急”其实根本没什么意义，因为我们不会因为一件事情足够重要，就变得可以控制它。例如，快毕业的时候，发表毕业论文当然是重要且紧急的事情，但是这件事依然不受我们控制，我们能控制的只是像多做几遍实验看看有没有好的结果，多给导师发几遍消息来试图获得更多的论文指导和修改意见之类的。

只去想那些我们可以控制的事情，虽然不起眼，或许更能帮助我们达到自己的目标。我打算用一本我没读过，但是当时书名很吸引我的书的书名来结尾。“你有你的计划，这个世界另有计划”
