---
title: 歧视：稀缺的必然结果
author: 思无邪
draft: false
date: '2025-04-16'
categories:
- 经济学
---
歧视 $or$ 选择？

<!--more-->

### 稀缺，无处不在

稀缺并非假设，而是基本事实（或许等到共产主义实现那天，人们就不用再研究经济学了，因为经济学基本上就是研究有限资源如何合理分配的学问）。生活中的几乎所有东西都是稀缺的，不仅是矿产，森林等看得见摸得着的东西，像是美貌、天资、地理位置还有信任等等这些抽象的东西也是稀缺的。

为什么会稀缺呢？主要原因有两个，一个是我们想要的东西别人也想要；另一个是人的欲望几乎是无限的。但是作为一个现代人，我常常反思是否很多欲望和需求是被人为制造出来的。经济学自然考虑过这个问题，我们来看看它是如何回答的。经济学完全承认很多的需求是被制造出来的，拿洗澡来举例，现在很多人大概觉得洗澡是天经地义的事情，包括在洗澡的时候在头发上涂洗发水，在身上涂沐浴液，似乎都是应该的。但是看看几十年前，洗澡是很少的事情，或者看看西藏某些部落，仍然是一生只洗三次澡。可以说洗澡某种意义上也是人为制造的欲望，但是慢慢的，这就成为了一个标准。我们今天的人，肯定比20年前，50年前的人更卫生、更干净。

### 我们在歧视的时候到底发生了什么？

歧视，或者选择或者说区别对待，一个意思的不同说法。稀缺必然导致歧视。因为资源是有限的，我们在运用有限的资源去选择性的完成一些事情（例如购买行为）的时候，就进行了歧视。例如，如果有100块钱，我们打算用来买一张专辑，买了陈奕迅的就买不了周杰伦的和其他歌手的，所以，在这次购买行为发生时，我们对除了陈奕迅以外的所有歌手进行了歧视。歧视在这里只是中性词。

#### 逆向歧视

为了消除歧视而产生的新的歧视就是逆向歧视。举一个美国的例子。1978年，美国发生了一个很著名的案子，叫“巴奇诉美国加州大学董事会案”(Regents of the University of California v. Bakke, 1978)。巴奇是一名工程师，参加越战后萌发了救死扶伤的愿望，要想报考大学学医。但是巴奇已经30岁了，当时美国大学有严重的年龄歧视，巴奇就被拒绝了。但是巴奇发现加州大学招生有一个特别条款，他在100个招生名额中，留了16个专门照顾弱势群体。巴奇觉得自己年龄偏大属于弱势群体，但是大学以他是白人不属于弱势群体拒绝了。巴奇便将学校告上法庭，这个案子打到最高法院，法院的意见是，学校根据学生种族因素予以照顾并不违宪，但是实施刚性的配额制度是违法的，最后巴奇被允许入学。这个案子形象的展示了逆向歧视是如何发生的。我们不应该问要不要歧视，而应该问如何歧视，其实就是问如何划定一个选择的标准。

### 歧视必有代价
#### 歧视的起源
歧视有两个起源，一个是偏好，这很好理解，但是这种原因导致的歧视难以消除，也没必要消除。另一个原因是信息不对称。例如假设房间里跳出来一只老虎，我们的第一反应肯定是赶紧跑。但这其实是以对一般老虎的印象来判断具体的老虎，是一种歧视，如果我们多花一点时间来了解这只老虎，没准会发现可能这只老虎是三代都在动物园里不咬人的那种老虎。但是如果有人以这种理由来劝你不跑，那你估计会觉得这个人是疯了。因为在那种情况下，花点时间了解的风险太高了，也就是说，获得“这只老虎吃不吃人”这条信息的费用在这种情况下非常的高，虽然以偏概全当然有可能发生错误，但是不这么干付出的成本相比，还是很划算的。
#### 歧视的代价
从歧视的起源我们就可以知道，人们歧视的原因有很大一部分是因为歧视的成本很低。那我们可以设想，如果歧视的成本变高，那人们就会为了降低损失而减少歧视的行为。那怎么提高歧视的成本呢？答案就是竞争。在竞争越激烈的地方，歧视的成本就越高。设想这样一个场景，有两家企业，一家是公营的，一家是私营的。由于在公营企业里招聘部门感受到的竞争压力小，所以就有更大的裁量权去选择更符合自己偏好的员工；而在民营企业里，由于竞争压力更大，如果他们放任自己的品味，就得承担较大的代价，所以用人就会更加的不拘一格，歧视行为就会受到抑制。

#### 限制歧视的后果

我们这次来看看2008年次贷危机的例子。在美国有各种各样的歧视，政府采取了大量措施来遏制歧视，但是这次我们要看的是遏制了本身合理的歧视会有什么后果。

从1960年开始，美国开始了轰轰烈烈的平权运动，来矫正社会的不公平现象。1991年，美国商业银行放贷数据被公开，人们发现能够拿到贷款大多数是白人，而少数族裔和弱势群体拿到贷款的可能性要低得多。1992年，联邦储备局波士顿分行发布了一份报告，声称根据严密的计算，美国商业银行一定对弱势群体进行了歧视。但实际上作为商业银行，没放贷给本来应该放贷的客户是银行的损失，但是群众并不相信。为了促使银行放贷，美国政府双管齐下。如果银行被调查发现歧视弱势群体就会被巨额罚款；并且让有政府背景的两家房地产公司——房地美和房利美——去收购商业银行的房贷合同，也就是房贷的贷款由政府承担风险（也是当时最主要的贷款）。

于是商业银行一下子就放松了对贷款人的审查，鼓励借款。但是银行都知道这种贷款是有毒的，因为那些没有还款能力的人很轻松的就拿到贷款了。所以银行们就把这些有毒的债务包装来包装去，买来买去，不知道最后会到谁手里，只要不在自己手里就好。同时银行相信“大而不倒”就是欠债越多，影响越广，政府就越不会让你倒。最后的结果就是2008年的次贷危机。