---
title: "多样性与效率"
author: "思无邪"
date: "2025-09-03 22:42"
categories: [梦话]
---

多样性和去掉多样性带来的好处可能是一样多的。

这个启发是最近看一篇关于中情局为什么无法预测911事件领悟的。故事是这样的，美国中情局在上个世纪的时候总是被举报种族歧视和性别歧视，原因很简单，里面只有白人、女性也极少。每次被提起公诉，中情局就大大方方的承认，确实只有白人，然后老老实实交罚款，但是却坚决不改。为什么呢？中情局的理由很简单，他是情报机构，是要为国家安全负责的，他们招进来的人都是经过严格考核符合标准的才能进来，是宁缺毋滥，总不能因为有种族歧视的嫌疑就放低标准，强行招一部分有色人种吧。这个道理看起来也是很充分。

但是，有一个事件就证明了中情局这种队伍，恰恰就摧毁了他的情报能力。这个事件就是911事件。911事后分析发现这次恐怖袭击之前有非常的线索。举几个例子，就在9·11事件前几周，有一个33岁的摩洛哥人，叫哈比卜·扎卡里亚斯·穆萨维的人，在一家国际飞行学校注册入学。开学才两天，他就引起了老师的怀疑，因为他付学费的方式与众不同：8300美元的学费，他用百元现钞支付了大部分。更怪异的是，他对驾驶舱门表现出了不同寻常的兴趣，并且不停地询问纽约市内及周边的航线状况。老师就报案了，联邦调查局也审了他，还搜查了他的住处，但是没有任何线索。像这样的事先的迹象，其实很多。

但是你想，美国那么大国家，在世界上又树敌那么多，怎么可能从海洋一般的噪音中，识别出有效的信息呢？比如，911发生前48小时，本·拉登竟“有胆量打电话给在叙利亚的母亲，并一五一十告知‘两天后，你将听到一个大新闻，之后我会和你断联一段时间’”。情报机构虽然拦截了这通电话，但是分析不出来这是什么意思。直到911发生之后，回溯此前的情报，才发现了这通电话。

再一深入调查，发现坏了，这还不只是一个噪音问题，而是中情局几乎就不可能把本·拉登识别出来。因为中情局自己给自己搞了一个认知黑洞。举个例子：1996年8月23日，奥萨马·本·拉登在阿富汗的一个山洞里向美国宣战。录像画面里是一个胡子及胸的男人，他衣着简单。当时，中情局的人是这么说的：“不相信这个胡子拉碴、蹲在篝火旁的高个子男人会构成什么威胁。”对啊，本·拉登看起来很原始啊，住在山洞里的一个人，要对抗全球顶尖的大国，他就是个疯子啊。一个疯子，要是也搭理他，中情局还干不干点正经事了？

但是本·拉登一点也不穷，他为什么要显得那么寒酸呢？本·拉登之所以选择洞穴，是因为它有着更为深层的象征意义。据说“穆罕默德从麦加成功脱身后，就是在一个山洞里避难。他所在的洞穴被一系列神圣的阻隔物包围起来——一棵原地生长出来、遮住入口的相思树，一些神奇的蜘蛛网和鸽子蛋，追兵因此认为洞穴里空无一人。”所以山洞本身就带着光环，本·拉登把自己幻化成“先知”，这个山洞就是他做对外宣传时的有利背景。他不是因为穷去了山洞，而是要刻意向全世界展现，他和先知之间的那种传承关系。

上面的例子是《多样性团队》这本书提出来的。

这种独属于阿拉伯文化的线索与信息，对于只有白人的中情局来说，就是一个巨大的认知黑洞，而造成这个黑洞的恰恰就是中情局那套只选精英的标准。所以《多样性团队》这本书里就说，不确定性的时代，“多样性”本身就是效率，就是能力。道理很简单，只要你追求单一的效率，你们的盲区就会叠加。

这个论证看起来很对，但是有一个问题。这个问题就是他要求我们不去追求效率。但是这太难了，几乎不可能。只有那些有一个主营业务及其赚钱的公司可以去放弃一部分效率去追求多样性。例如微软、Google等等。他们不用刻意追求效率，他们的目的是不被时代落下，所以他们鼓励去尝试各个方向的技术，希望在诞生下一个革命性的技术的时候，自己依然在牌桌上。但是也只有这些大公司能做到，因为他们太有钱了，不论在探索的路上怎么输，永远可以从兜里掏出一把钱来，要求再来一把。世界上又有几个微软、Google这样的公司呢？其他稍小一点的Google效率稍微低一点，马上就被竞争对手超越，随时有可能被淘汰啊。

你可能纳闷我这篇博客到底想说啥呢？多样性到底好不好呢？其实我想说的是，多样性和高效率，是达成目标的两种不同的方法，但是，鱼和熊掌不可兼得。大自然，从来都是通过多样性来达成目标的，比如，春天的池塘里全是蝌蚪，没有几个会变成青蛙；我们今天能变成一个大活人，也是在2亿个小伙伴的竞争中胜出的结果。为什么会有两性生殖？就是为了更多的多样性，牺牲了效率。而在个体的角度，会用另一种策略达成目标，那就是低成本、高收益的效率导向。多样性是被排斥的。过去200年的工业革命就是最好证据，我们通过分工合作，降低了每一个人的多样性但是极大的增加的效率，恰恰是这种方法为人类社会带来了巨大的繁荣。

难道我们作为个人真就没有一点办法吗？结合我最近的学习的体验，我想我们或许可以学习学习微软、Google他们的做法，这个想法很俗，也没什么新意，但是这是我目前想到的唯一的还凑合的方法。就是在保证主业的前提下，留点时间去搞搞其他的东西，给自己适当的增加些多样性，但缺点是要求我们在主业有绝对的高效率。就像我没事写写博客一样，也算是增加自己的多样性。但为什么更新这么慢呢？因为我在主页的效率并没有那么高(希望能再高些吧)，哈哈。

以上。