---
title: 伯林：是否存在最高的价值？
author: 思无邪
draft: false
date: '2025-04-11'
categories:
- 西方现代思想
---
我们在做出决断时到底牺牲了什么？
<!--more-->

### 多元价值论

我们知道，所谓“价值”指的是那些我们认为重要的理念，比如平等、正义、自由、爱、善良、仁慈……你的价值观，就是指你信奉或者珍视什么理念。这些理念构成了你人生意义的基础，也是你为自己的生活确立目标的依据。

那价值多元论是什么意思呢？就是主张人们追求的价值不是单一的，而是多种多样的。而对于“什么是美好的生活”这个问题，价值多元论者认为，理性无法给出唯一正确的答案。

这么来看多元价值论似乎没有什么新鲜的，似乎有些过于显然和浅薄了。但其实多元价值论最重要的一点是认为各种各样的价值之间是无法转化的，各种价值之间经常会产生不可调和的矛盾。

为了解释它，我们最好来看看一元价值论说了什么。

价值一元论并不是说世界上只有一种价值，或者人只能追求一种价值，它主张的是，表面上有丰富多样的价值，但这些价值在本质上是和谐统一的。

这样一来，表面上有多种多样的价值，实际上它们可以相互兼容，彼此之间也不会发生真正的冲突。于是从价值一元论就可以引申出一个推论，就是对于“什么是美好的生活”这个问题，存在唯一正确的答案，能让你做出最好的选择。

但是伯林认为，一元价值只是一种幻觉。他说，多元价值之间的冲突是不可能消除的。如果执着于价值一元论，就很容易会去压制其它的价值和理想，干涉甚至毁灭多种多样的生活方式，结果往往在实践中造成巨大的灾难。

伯林说，我们追求的许多价值，它们之间是不能换算的，都是彼此独立的“终极价值”。你不能说实现了自由其实就实现了某种程度的平等，反过来也一样。换言之，某一种价值并不是其它价值的派生物，不能被还原为其它的价值。

> 我们要在同等终极的目的、同等绝对的要求之间做出选择，且某些目的之实现必然无可避免地导致其它目的之牺牲—所以，（我们）需要选择，需要为了一些终极价值牺牲另一些终极价值，这就是人类困境的永久特征。
>
> <p align="right">——伯林</p>

### 自由？

伯林还有一个最重要的成就，就是重新澄清了自由这个概念。

#### 消极自由和积极自由

伯林认为自由分为两种，一种是消极自由，另一种是积极自由。消极自由就是我不想做的时候可以不做的权利，而积极自由是我想做某件事时就可以做的权利。

我们来详细的阐释一下他们的区别。消极自由强调有一个“不受干涉”的领域，更像是一种机会，只要保留这个机会，即使什么也不做，这种自由就依然存在。而积极自由却不行，积极自由是实现某种事情的自由，你必须去行动的实现它，例如你想锻炼来强身健体，但是又偷懒没有行动，那么就没有实现积极自由，也就是抛弃了积极自由。

#### 对自由的滥用

设想一个场景。你开车去上班，马上就要迟到了，但这时你突然犯了烟瘾，很想绕路先去买包烟。可是这时，坐在副驾驶上的你的好朋友说话了，他劝你不要这样做。你对他说，你别管我，这是我的自由。你的朋友发脾气了，他说这不是真正的自由。他逼你下车，让你坐到后座，然后他来开车，把你送到了公司。你有点不高兴，但他说这样做是“为了你好”，你想了想，觉得他说得也对。一个月之后，你厌倦了这份需要“996”的工作，想要辞职不干了。你的朋友又出现了，他劝导你说，这个工作最符合你的长远利益，你现在太年轻、不懂事，必须听他的教导，他甚至每天早上亲自来把你绑上车送到公司。他说，这个工作才是你真正想要的，虽然现在你还不明白。那么现在，表面上他强制了你，但在本质上是帮助你实现你一时还不明白的、却是你真正想要的目标，让你得到了更高的自由。

看到后面是感觉非常的诡异呢？有种毛骨悚然的感觉，这个设想里的“朋友”其实可以代指任何一种权威。通过滥用积极自由的概念，把强迫说成了自由。我们来看看到底问题出在哪。

伯林明确说过，消极自由和积极自由都是正当的终极价值，原则上没有高下之分。但这两种自由都可以被滥用和扭曲，伯林想强调的是，积极自由的扭曲和滥用更具有欺骗性，更要对其保持警惕。伯林承认，在特定情况下，强制可能是必要的，消极自由有可能需要向其它价值让步，甚至做出牺牲。但是，牺牲就是牺牲。当自由必须被牺牲的时候，我们就应该说“这是牺牲了自由”换来了安全、秩序或者别的什么。而不应当玩弄“概念魔术”，把牺牲改头换面变成“更高的自由”。如果因为一个人幼稚、蒙昧……必须强制他才能使他不受害，那么就应该说，这是为了他自己的利益而对他实施了强制。但正当的强制依然是强制，不能被曲解为“顺应了他真正的意愿”。



