---
title: 尼采：只有当你全部否定我的时候才是真正理解了我
author: 思无邪
draft: false
date: '2025-04-08'
categories:
- 西方现代思想
---
如何面对人生的虚无

### 上帝死了

> 上帝死了，是我们杀死了上帝！这个世界上最神圣、最万能的上帝，现在已经倒在我们的刀下。我们这些最残忍的凶手，如何才能洗清我们身上的血迹啊？
>
> <p align="right">——尼采</p>

上帝代表了人的信仰，人在不确定的世界里需要信仰的安慰，但这种安慰往往只是虚假的，而尼采把形而上学当作虚假的思想，尼采认为形而上学有三大信念：

第一，相信在感知的表象世界背后有一个更真实的本质世界；

第二，相信这个混乱的世界实际上是有目的的；

第三，相信这个纷乱多样的世界背后有一种统一性。

但是尼采认为，那个所谓更真实的、有目的的、有统一性的本质世界根本不存在。哪有什么比现实更真实的世界，有人真正看见过吗？根本没有，这就是形而上学的编造，之所以编造是因为我们需要这些虚假的思想带来的安慰，通过这些虚假的思想里提供的“人生终极目标”来逃避真实的问题。

尼采认为，生命欲望是真实的，也是正当的。即使因为挫折而痛苦，我们也应当直面它们。

如果我们相信虚假思想，就是把生命的希望寄托在不可靠的事物上面。当它们和生命本能冲突，我们就会怀疑这些虚假思想。结果是把我们寄托在上面的希望给打破了，人陷入虚无当中。所以在尼采看来，那些看上去高尚典雅、充满确定感的形而上学才是虚无主义的真正根源。

那么在上帝被杀死后，面对虚无，人们又该怎么做呢？

### 积极的虚无主义

面对虚无，大部分人似乎都觉得很悲观，感觉是很不好的事情。但尼采不这么认为，尼采认为人生本质就是虚无，人们之所以觉得虚无悲观，是因为之前一直被虚假的思想带来的那种“人生有一个终极的目标或者意义”给蒙骗了，而在知道人生虚无之后就会产生失落感，从而导致悲观。

打个比方，假设你去参加马拉松，有人告诉你冲过终点会得到一个奖杯，你要是把奖杯当作目标，满怀希望的冲过终点却发现根本没什么奖杯的时候，就会很失望。但是如果一开始你就不知道，或者没想奖杯的事，那你冲过终点时就不会感觉失望了。

但是自古以来，许多哲学家都在告诉大家人生的终点是有奖杯的，只不过被换成了各种所谓的真理或者绝对信仰，这掩盖了人生本就虚无的真相。尼采想要把这些虚无的思想的彻底砸碎，把以前那些哲学家建立的人生目标，人生意义全部抛弃，让人们直面虚无的绝境。

那现在人们站在虚无面前，人生没有意义，那他还拥有什么呢？尼采认为人还有生命力。

首先，尼采认为虚无不导致消极，这一点已经在上面阐述清楚了。而且尼采认为认识到世界本无意义，恰恰带来了创造的自由，尼采觉得价值不是现成在哪里等你“发现”，所有的价值都是人主观创造出来的，生命活动的标志就是能够自己确立价值，这是生命本身的力量。

面对无意义的世界和无意义的生命，人应该立足于现实，直面无意义的荒谬，以强大的生命本能舞蹈，在生命活动中创造出价值。用尼采的话说，就是“成为你自己”。这样一来，虚无不再会让你沮丧和绝望，反倒会给你最广阔的创造自我意义的空间，虚无让人变成了积极的创造者，这就是积极的虚无主义。

### 超人

> 登上顶峰的斗争本身足以充实人的心灵。应该设想，西西弗斯是幸福的。
>
> <p align="right">——加缪</p>

对于积极的虚无主义，最典型的例子就是西西弗斯。西西弗斯的命运象征着人生的困境，一切都是徒劳。但西西弗斯还有一个最终的选择。他可以选择在这个过程中沮丧绝望，充满怨恨和悲哀，让这件事变成最痛苦的折磨。但他还可以做另一种选择，就是勇敢无畏地、精神焕发地去推动这块巨石。这样一来，这件事就不再是无意义的。西西弗斯用自己的选择创造出了意义，用无尽的斗争精神去对抗虚无。

尼采把前一种选择称为奴隶道德，后一种为主人道德。你可能会想，后一种选择难道不是很难吗？所以尼彩呼唤一种新的人类，就是能做出并做到第二种选择的人类，他把这种人称为超人。

### 激进的否定性

很多人在看了尼采的思想之后，会自然的想到一个问题：尼采的学说会不会也是一种虚假的观念？如果我相信尼采的说法，不也是把自己的生命希望寄托在别人的理论之上吗？

让我们来看看尼采本人是怎么说的。

> 你们说相信扎拉图斯特拉，但扎拉图斯特拉算什么？你们说是我的信徒，但所有的信徒又算得了什么？你们没有探索自己，却发现了我……现在我要你们丢开我去发现自己，只有当你们全部否定我的时候，我才会回到你们身边。
>
> <p align="right">——尼采</p>

所以，如果你相信尼采，那就不该盲从尼采，因为如果你真的理解了他的思想，就不应该相信任何人包括尼采本人写下的教条，而是去探索自己的生命。

### 结尾

尼采的虚无主义是一个坏消息，同时又是一个好消息。坏消息是人生是虚无的，理论文化也是虚假的。但它又是一个好消息，因为虚无的真相留出了最自由的空间，我们完全可以积极面对，用生命本身的力量创造自己生命的意义。能做到这一点，就是尼采所说的超人。不过，尼采极端的否定精神，也会带来巨大的问题：如果所有价值都是人创造的，那价值与价值之间还有好坏对错之分吗？虽然尼采用积极的虚无主义代替了消极的虚无主义，但又带来另外一个巨大的问题：我们凭借什么创造，自我创造是否有一个评判标准，怎么判断我们的创造是好是坏？

这个疑问以后我们再来回答。
