---
title: 关于投射
author: 思无邪
draft: false
date: '2025-03-19'
categories:
- 梦话
---
投射，动词，指类似“望子成龙”等将自己的情感需要或者愿望强加于他人的现象，与共情相反。
<!--more-->
前几天我讨论过“倾听"这个词，昨天晚上和同学在微信上聊天。我发现我根本做不到所谓”倾听“的境界。其实在聊天的过程中，我一直在聊自己，也就是今天想要说的”投射“。这种对话当然是很拧巴的，很快我也意识到了，不过当时大概心情不咋地或者之类的，也没有改正自己的行为。

关于投射，最经典的场景莫过于别人给我们意见，其实生活中别人给我们意见时，其实并非给我们意见，大概率只是在给他们自己意见（包括父母）。他们可能只是想要表达自己的想法，但是让你去”帮他们实现“罢了，如果你真的实现了，那他们大概还会来说”你看我当时说得没错吧“巴拉巴拉一大堆证明自己的智慧（很遗憾我自己目前就是这种人，我发现这真招人讨厌，可能我内心是个讨好型人格但是不知道为啥表现出来是个讨人厌型人格，我活得可够拧巴的）；如果你按照他们的意见失败了，那他们也不会承担任何的责任，甚至大概率要指责你没有”忠诚“的履行他们的意见，他们没有错，只是你执行错了；如果你没听，还还失败了，那他们大抵会对你冷眼相待，或者说”要是你当时听我的不就没这回事了吗？“对着你一顿阴阳怪气；最有趣的莫过于你没听他们的建议但是还成功了，这下可就有好戏看了，往往有两种情况，一种是不闻不问，其实不论是你听没听取他们的意见，大部分时候他们都是这个反应，毕竟他们只是在给出他们自己意见，有没有真的在关心你，但也有可能会有些恼火，责怪你为何没按他们说的做，因为你浇灭了通过你来实现他们愿望的希望。

对于对方给你建议时是否是在投射，一个简单的判断方就是看对方会不会因为你没有按他的指示去做而生气。真正的关心和建议是不会在意你是否听取的，只关心你最后有没有解决你自己的问题，如果问题本身得到了解决，那方法是什么又有什么关系呢？作为朋友、家人或者亲人，他们应该会为感到高兴，而非恼火。

可悲的是按照这个标准，我在与朋友、家人的相处中，似乎从来没有真正关心过别人，从来只有对他们的”投射“。不过，按照我的性格，我还是会觉得这一定是他们的问题，绝对不是我的问题，如果他们怎么怎么着，我肯定就不会这样啦（看来其实内心也是讨人厌型人格呢）。