---
title: 科斯定律：社会成本问题
author: 思无邪
draft: false
date: '2025-04-19'
categories:
- 经济学
---
风俗习惯和道德规范为何重要？
<!--more-->
### 案例引入
#### 案例一：泳池阳光与酒店副楼（FontaineBleau Hotel v. Forty–Five Twenty–Five ,1959）
有两家相邻的酒店，左边的酒店，有一个漂亮的游泳池；右边的酒店，要在自己的土地上盖一幢14层高的副楼。要是这幢副楼盖起来，就会挡住游泳池的阳光。游泳池没有阳光，游客可能减少，酒店的收入就会受影响。于是，左边的酒店跑到法院，要求法院颁布法令，禁止右面的酒店盖副楼。如果你是法官，会怎么判？
#### 案例4：火车与亚麻（LeRoy Fibre Co. v. Chicago, Milwaukee and St. Paul Ry. ,1914）
从前的火车都是烧煤的，烧煤就会喷出火星。有一辆火车路过一片亚麻地，农夫把700吨亚麻堆在了铁路边自己的农地上。这亚麻是农夫的，铁路边的农地也是农夫的。亚麻放在农地上，没有碍任何人的事儿，但是火车经过时喷出的火星把700吨亚麻给烧了，铁路公司要不要赔偿？
#### 水泥厂与老居民（Boomer v. Atlantic Cement Company, 1970）
一家水泥厂长年排放各种灰尘，散发出臭味，有时甚至还会发出震动，对周围环境造成了严重污染。居民就去告水泥厂，要求赔偿。居民的控诉，并不是一次两次，他们隔三岔五就去告水泥厂，并不时拿点补贴。如果你是法官，会怎么判？

之所以讲这么多例子，是因为这些例子有一个共同点，那就是一方伤害了另外一方。我们的问题是，是否要判伤害者做出赔偿？对于大众而言，答案是非常明显的，伤害者当然要对被伤害者做出赔偿，同时，我们还要限制伤害者对周边居民、周边环境继续造成伤害。所有人都这么看，只有一个人不同意，这个人就是罗纳德·科斯。
### 科斯的非凡见解
科斯的看法则别具一格，他说所有的伤害都是相互的，我们得用新的眼光来看待这些案例：不是一方在伤害另外一方，而是双方为了不同的用途，在争夺相同的稀缺的资源：牛跟小麦争的是那块地，如果让牛吃小麦，那牛就伤害了小麦；但如果禁止牛吃小麦，小麦就伤害了牛。

关于科斯理论的争论，法律经济学者、芝加哥大学法学院教授理查德·爱泼斯坦（Richard Epstein）曾提出过一个观点。他说，如果争夺资源的双方是同一个人，那会发生什么情况？以这样的角度来重新审视前面提到的案子，可能就会豁然开朗了。

拿火车与亚麻的的例子来说，在现实生活中，如果铁路公司和农地同属一人，他当然会说：”我只要把堆放亚麻的地点挪远一点，意外就能避免了。“

这个想法非常重要。正是基于这个想法，科斯的意思是说，火星烧着了亚麻，但是责任可能在农夫，虽然农夫并未招惹铁路公司。谁付出的成本更低，谁就应该承担更大的责任。那既然农夫避免意外所要付出的成本，比铁路公司避免意外所要付出的成本低得多，那挪开亚麻的责任，就要落到农夫身上了。通过这样的责任分摊方式—推而广之，用到各种责权利的分配上—整个社会为了避免意外所要付出的总成本就会降到最低。
### 隐私权与公共安全的权衡
大数据的使用，经常引发隐私权应该归谁的问题。好多人对隐私权非常敏感，觉得隐私权一点都不能出让。当然，我们能够理解这种感受。我们今天晚上跟谁在一起，跟谁吃烛光晚餐，跟谁坐飞机出去旅游，这些数据对别人来说可有可无，但对我们自己来说非常重要，所以保护隐私确实很重要。

但是有些犯罪分子的数据公安机关拿到后就能发挥极大的作用，避免很大的损失。那公安机关是不是也应该有一些权力，征用个人的隐私权呢？

从科斯的见解来看，这种争论绝对不会一边倒，最后会取得一个平衡，最终还是遵从科斯定律：谁用的好就归谁。



待续……